# Generated by Django 4.2.1 on 2023-05-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0004_alter_pizza_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='photo',
            field=models.ImageField(upload_to='pizzashopapp/static/pizzashopapp/img/'),
        ),
        migrations.AlterField(
            model_name='soup',
            name='photo',
            field=models.ImageField(upload_to='pizzashopapp/static/pizzashopapp/img/'),
        ),
    ]
