# Generated by Django 4.2.1 on 2023-06-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0007_bascet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bascet',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
